CREATE TABLE IF NOT EXISTS users (
	id SERIAL PRIMARY KEY,
	name VARCHAR (50) NOT NULL, 
	username VARCHAR (50) UNIQUE NOT NULL,
	email VARCHAR (255) UNIQUE NOT NULL,
	password TEXT UNIQUE NOT NULL,
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
